# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: product_control_api_development

test:
  <<: *default
  database: product_control_api_test


production:
  <<: *default
  database: product_control_api_production
  username: product_control_api
  password: <%= ENV['DB_PASSWORD'] %>
